server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root
  application:
    name: "cards"
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: "5672"
    username: "guest"
    password: "guest"
  profiles:
    active: "prod"

management:
  endpoints:
    web:
      exposure:
        include: "*"