spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ElshanDunyamaliyev/Configuration-for-Config-Server.git"
          timeout: 5
          default-label: master
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: "5672"
    username: "guest"
    password: "guest"
#    config:
#      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///home//elshan//config"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true